angular.module('myApp', []).controller('namesCtrl', function ($scope) {
    $scope.names = [
        { name: 'Jani', country: 'Norway' },
        { name: 'Hege', country: 'Sweden' },
        { name: 'Kai', country: 'Denmark' }
    ];

    $scope.levels = [ "", "100", "200", "300"];
    $scope.tris = [ "", "1", "2", "3"];

    $scope.setSelected = function(z) {
        $scope.selected = z;
        $scope.directoryShow = false;
        $scope.buildingInfo = true;
      };

    $scope.setSelectedjob = function(z) {
        $scope.selectedjob = z;
    };

    $scope.myFunction1 = function(z) {
        // alert(z);
        // document.getElementById("courseinput1").value = z;
        $scope.selected = z;
        // this.css("background-color", "red");
        // elmnt.style.color = clr;
    };

    $scope.myFunction2 = function(z) {
        alert(z);
        // document.getElementById("courseinput1").value = z;
        $scope.setSelectedjob = z;
        // this.css("background-color", "red");
        // elmnt.style.color = clr;
    };

    // $scope.courseclick = function (item) { 
    //     // alert(item);
    //     return item;
    // };

    $scope.alert = function(arg){
        alert(arg);
    }

    angular.module('myFilters', []).
  filter('bygenre', function() {
    return function(movies,genres) {
      var out = [];
      // Filter logic here, adding matches to the out var.
      return out;
    }
  });
  
    $scope.cous = [
        {tri1: 'Trimester 1', time1: 'Monday - 09:00 & Thursday - 09:00 ', loc : 'Kelburn',
        tri2: 'Trimester 1', time2: 'Monday - 16:10 & Wednesday - 16:10 ', 
        tri3: 'Trimester 2', time3: 'Tuesday - 12:00 & Thursday - 12:00 ',
        tri4: 'Trimester 2', time2: 'Tuesday - 11:00 & Thursday - 11:00 ', 
        ass1: 'Writing quiz:', mark1:'5%', ass2: 'Essay 1: 10%', mark2: '10%', ass3: 'Workshop quizzes (HTML/CSS/JS)', mark3: '15%', ass4: 'Essay 2' , mark4 : '15%', ass5: 'Project (Website)', mark5: '25%', ass6: 'Exam (2 hours)', mark6: '30%'
}

];
    $scope.courses = [
        { course: 'INFO 101', bcolor: 'success' , courseName: 'Introduction to Information Systems', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 1 and 2', tri1: '1', tri2: '2', description: 'This is a foundation course to information systems. In this paper you will get to learn about the fundamental concepts of information systems and you will get to use HTML, CSS and JavaScript to code a website', image: '', icon: 'images/INFO 101.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', coordinator:'Janet Toland and Michael Winikoff' },
        { course: 'INFO 141', bcolor: 'success' , courseName: 'Systems Analysis', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 2', tri2: '2', description: 'INFO 141 covers business analysis (identifying business needs and determining solutions to business problems) and system analysis (interpreting facts, identifying problems) activities, from the perspective of a business analyst.', image: '', icon: 'images/INFO 141.jpg',url: 'https://www.victoria.ac.nz/courses/info/141/2020', coordinator:'' },
        { course: 'INFO 151', bcolor: 'success' ,courseName: 'Databases', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 1 and 3', tri1: '1', tri3: '3',  description: 'This course introduces the principles of database definition, design, access and implementation. ', image: '', icon: "images/INFO 151.jpg",url: 'https://www.victoria.ac.nz/courses/info/151/2020', coordinator:'' },
        { course: 'INFO 231', bcolor: 'success' ,courseName: 'Management of IT Projects', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141 or 151, or 15 COMP pts', it:'IT' , is: 'BA', tri: 'Trimester 1',tri1: '1', description: 'This course is a detailed examination of IT project management including initiating, planning, executing, controlling and closing the work of IT projects. You will also gain an appreciation of IT risk and change management strategies.', image: '', icon: 'images/INFO 231.jpg',url: 'https://www.victoria.ac.nz/courses/info/231/2020', coordinator:'' },
        { course: 'INFO 234', bcolor: 'warning' , courseName: 'Business Process Design', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141, or 151', it:'' , is: 'BA', tri: ' Trimester 2', description: 'This course explores the role and potential of IT to support business process management and design. You will use modern business process modelling techniques to improve business processes, then test and evaluate their proposed design using simulation software.   ', image: '', icon: 'images/INFO 234.jpg',url: 'https://www.victoria.ac.nz/courses/info/234/2020', coordinator:'' },
        { course: 'INFO 264', bcolor: 'warning' , courseName: 'Business Analytics', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'' , is: 'BA', tri: 'Trimester 2', description: 'Covers the techniques of collecting, organising and analysing historic data to improve business proceses and predict customer behaviour. Uses analytical software for data mining, decision support, supply chain management, simulation, and optimisation', image: '', icon: 'images/INFO 264.jpg',url: 'https://www.victoria.ac.nz/courses/info/264/2020', coordinator:'' },
        { course: 'INFO 226', bcolor: 'primary' , courseName: 'Application Development', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'IT' , is: '', tri: 'Trimester 1 ', description: 'This course is an introduction to the use of software languages and tools for rapid application development. You will use Trello to manage a project and Plunker as a development tool. ', image: '', icon: 'images/INFO 226.jpg',url: 'https://www.victoria.ac.nz/courses/info/226/2020', coordinator:'' },
        { course: 'INFO 246', bcolor: 'primary' ,courseName: 'User Experience Design', Points: '15 Points', level: '200', Prerequisites: 'INFO 101 or 141 or 151', it:'IT' , is: '', tri: 'INFO101, 141 or 151.', description: 'This course introduces fundamental principles, standards and best practices of human-computer interaction, usability and user experience ', image: '', icon: 'images/INFO 246.jpg',url: 'https://www.victoria.ac.nz/courses/info/246/2020', coordinator:'' },
        
        
        { course: 'INFO 354', bcolor: 'success', courseName: 'Digital Strategy', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1', description: "This course will allow you to develop your competence in seeing how organisations can benefit from digital technology, converting opportunities created by technology into sustainable organisational value. You will learn through discussing cases from well-known companies such as DropBox, Cirque du Soleil, Twitter, Amazon and also from more obscure innovators. ", image: '', icon: 'images/INFO 354.jpg',url: 'https://www.victoria.ac.nz/courses/info/354/2020', coordinator:'' },
        { course: 'INFO 376', bcolor: 'success' ,bcolor: 'success', courseName: 'Enterprise Architecture', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1', description: "This course addresses the alignment between enterprise goals and strategy, business processes, data, information systems and the technical infrastructure.", image: '', icon: 'images/INFO 376.jpg',url: 'https://www.victoria.ac.nz/courses/info/376/2020', coordinator:'' },
        { course: 'INFO 334', bcolor: 'warning' , courseName: 'Digital Business Innovation', Points: '15 Points', level: '300', Prerequisites: 'INFO234', it:'' , is: 'BA optional', tri: 'Trimester 3', description: 'The course focuses on how businesses can adapt information technologies to add innovation to business models, products and services. It will allow you evaluate real life examples and apply your learnings to innovations of your choice. s', image: '', icon: 'images/INFO 334.jpg',url: 'https://www.victoria.ac.nz/courses/info/334/2020', coordinator:'' },
        { course: 'INFO 388', bcolor: 'warning' , courseName: 'Enterprise Security', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'' , is: 'BA optional', tri: 'Trimester 1 ', description: 'This course explores current managerial and technical information security topics. You will learn proven information management approaches, methods, techniques and tools and how to apply these to control prevalent threats and risks.  ', image: '', icon: 'images/INFO 388.jpg',url: 'https://www.victoria.ac.nz/courses/info/388/2020', coordinator:'' },
        { course: 'INFO 377', bcolor: 'primary' ,courseName: 'System Verification', Points: '15 Points', level: '300', Prerequisites: 'INFO226', it:'IT optional' , is: '', tri: 'Trimester 2', description: 'In this course you will apply the theory of information systems assurance to design and build test plans for specific systems and software requirements.', image: '', icon: 'images/INFO 377.jpg',url: 'https://www.victoria.ac.nz/courses/info/377/2020', coordinator:'' },
        { course: 'INFO 386', bcolor: 'primary' , courseName: 'Information Technology Architecture', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'IT Optional' , is: '', tri: 'Trimester 1', description: 'This course examines conceptual and physical building blocks of current information and communication infrastructures, including distributed, mobile, pervasive and cloud solutions. In your workshops you will be using Raspberry Pi to explore computing and learn how to program in languages like Scratch and Python.', image: '', icon: 'images/INFO 386.jpg',url: 'https://www.victoria.ac.nz/courses/info/386/2020', coordinator:'' },

        { course: 'INFO 336', bcolor: 'secondary' ,courseName: 'Social Responsibility in a Digital World', Points: '15 Points', level: '300', Prerequisites: ' 15 200-level INFO or COMP/ NWEN/SWEN pts', it:'' , is: '', tri: 'Trimester 1', description: 'This course is a critical examination of the relationship between digital technologies and systems and concerns centred on sustainability and social justice. Topics will focus on current issues regarding both sustainability in the context of organisations, communities, government and society.', image: '', icon: 'images/INFO 336.jpg',url: 'https://www.victoria.ac.nz/courses/info/336/2020', coordinator:'' },
        { course: 'INFO 360', bcolor: 'secondary' ,courseName: 'Information Systems for Health Care', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'' , is: '', tri: '', description: 'This course will enable students to apply practical cases using modelling technologies to enable students to acquire and practice the skills necessary to define and implement health information systems.  ', image: '', icon: 'images/INFO 360.jpg',url: 'https://www.victoria.ac.nz/courses/info/360/2020', coordinator:'' },
        { course: 'INFO 381', bcolor: 'secondary' ,courseName: 'Special Topic: Topics in Applied Machine Learning', Points: '15 Points', level: '300', Prerequisites: 'one of INFO264, 281, MATH141, 251, 277', it:'' , is: '', tri: 'Trimester 2', description: 'In this course you will learn about the principles and applications of advanced machine learning models. You will carry out the preparation and processing required for selecting input data for machine learning models, quantitatively evaluate and qualitatively interpret the outcomes of model learning or prediction ', image: '', icon: 'images/INFO 381.jpg',url: 'https://www.victoria.ac.nz/courses/info/381/2020', coordinator:'' },
        { course: 'INFO 391', bcolor: 'secondary' ,courseName: 'Research Paper in Information Systems', Points: '15 Points', level: '300', Prerequisites: 'Permission of Head of School, 30 300-level INFO pts', it:'' , is: '', tri: 'Trimester 1, 2 & 3', description: 'This course is a supervised investigation of information systems issues. The investigation may take the form of a case study, action research, extended research essay, or other research project. ', image: '', icon: 'images/INFO 391.jpg',url: 'https://www.victoria.ac.nz/courses/info/391/2020', coordinator:'' },
        { course: 'INFO 320', bcolor: 'primary' ,courseName: 'Project in Information Systems', Points: '15 Points', level: '300', Prerequisites: 'B+ or better in any 2: INFO 226, 231, 234, 246, 264; & 15 INFO 300 pts', it:'IT Capstone' , is: 'BA Capstone', tri: '', description: 'This course provides students with an opportunity to apply their theoretical knowledge to a practical problem in the area of information systems. Students work in teams on real projects for real clients. The course coordinator defines the projects.', image: '', icon: 'images/INFO 320.jpg',url: 'https://www.victoria.ac.nz/courses/info/320/2020', coordinator:'' },
        { course: 'INFO 395', bcolor: 'warning' , courseName: 'Case Studies in Information Systems', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts, and 15 300-level INFO pts', it:'' , is: 'BA Capstone', tri: 'Trimester 2', description: 'In this course you will analyse the human, organisational, and environmental perspective of the impact of new or existing information systems, including management of IT-induced change. ', image: '', icon: 'images/INFO 395.jpg',url: 'https://www.victoria.ac.nz/courses/info/395/2020', coordinator:'' },
    ];

    $scope.courseshort = [
        { course: '101', bcolor: 'success' , courseName: 'Intro to Information Systems', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 1 and 2', tri1: '1', tri2: '2', description: 'This is a foundation course to information systems. In this paper you will get to learn about the fundamental concepts of information systems and you will get to use HTML, CSS and JavaScript to code a website', image: '', icon: 'images/INFO 101.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', coordinator:'',
        tes: 'Course Testimoials',student: 'Randall Smith,', status: 'Graduate', course1: 101, p1: "INFO101 was a great launching point into the various specialisations within information systems and critically for me, technical topics were delivered in a very 'business'/ easy to understand manner that meant, as a non-technologist starting off, I was able to get across key technology concepts quickly!",
        tri1: 'Trimester 1', time1: 'Monday - 09:00 & Thursday - 09:00 ', 
        tri2: 'Trimester 1', time2: 'Monday - 16:10 & Wednesday - 16:10 ', 
        tri3: 'Trimester 2', time3: 'Tuesday - 12:00 & Thursday - 12:00 ',
        tri4: 'Trimester 2', time4: 'Tuesday - 11:00 & Thursday - 11:00 ', 
        lect: 25, work: 10, tut: 5, prep: 40, asses: 70, loc: 'Kelburn Campus',
        ass1: 'Writing quiz:', mark1:'5%', ass2: 'Essay 1: 10%', mark2: '10%', ass3: 'Workshop quizzes (HTML/CSS/JS)', mark3: '15%', ass4: 'Essay 2' , mark4 : '15%', ass5: 'Project (Website)', mark5: '25%', ass6: 'Exam (2 hours)', mark6: '30%' },
        { course: '141', bcolor: 'success' , courseName: 'Systems Analysis', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 2', tri2: '2', description: '141 covers business analysis (identifying business needs and determining solutions to business problems) and system analysis (interpreting facts, identifying problems) activities, from the perspective of a business analyst.', image: '', icon: 'images/INFO 141.jpg',url: 'https://www.victoria.ac.nz/courses/info/141/2020', coordinator:'',
        tes: 'Course Testimoials',student: 'Manraj Rahi,', status: 'Current Student',course1: 141, p1: "Choosing my favourite paper is tricky. INFO141 was the paper where I felt I gained an appreciation of what a Business Analyst would do and the practical skills required - I found this really valuable. In general, I’ve thoroughly enjoyed the practical elements of the program; actually being given a chance to apply the skills you learn in lectures meant the INFO degree has lived up to - and exceeded - expectations. " },
        { course: '151', bcolor: 'success' ,courseName: 'Databases', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 1 and 3', tri1: '1', tri3: '3', description: 'This course introduces the principles of database definition, design, access and implementation. ', image: '', icon: "images/INFO 151.jpg",url: 'https://www.victoria.ac.nz/courses/info/151/2020', coordinator:'' },
        { course: '231', bcolor: 'success' ,courseName: 'Management of IT Projects', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141 or 151, or 15 COMP pts', it:'IT' , is: 'BA', tri: 'Trimester 1', tri1: '1', description: 'This course is a detailed examination of IT project management including initiating, planning, executing, controlling and closing the work of IT projects. You will also gain an appreciation of IT risk and change management strategies.', image: '', icon: 'images/INFO 231.jpg',url: 'https://www.victoria.ac.nz/courses/info/231/2020', coordinator:'' },
        { course: '234', bcolor: 'warning' , courseName: 'Business Process Design', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141, or 151', it:'' , is: 'BA', tri: ' Trimester 2',tri2: '2', description: 'This course explores the role and potential of IT to support business process management and design. You will use modern business process modelling techniques to improve business processes, then test and evaluate their proposed design using simulation software.   ', image: '', icon: 'images/INFO 234.jpg',url: 'https://www.victoria.ac.nz/courses/info/234/2020', coordinator:'' },
        { course: '264', bcolor: 'warning' , courseName: 'Business Analytics', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'' , is: 'BA', tri: 'Trimester 2', tri2: '2', description: 'Covers the techniques of collecting, organising and analysing historic data to improve business proceses and predict customer behaviour. Uses analytical software for data mining, decision support, supply chain management, simulation, and optimisation', image: '', icon: 'images/INFO 264.jpg',url: 'https://www.victoria.ac.nz/courses/info/264/2020', coordinator:'' },
        { course: '226', bcolor: 'primary' , courseName: 'Application Development', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'IT' , is: '', tri: 'Trimester 1 ', tri1: '1', description: 'This course is an introduction to the use of software languages and tools for rapid application development. You will use Trello to manage a project and Plunker as a development tool. ', image: '', icon: 'images/INFO 226.jpg',url: 'https://www.victoria.ac.nz/courses/info/226/2020', coordinator:'',
        tes: 'Course Testimoials',student: 'Patrick Miller,', status: 'Graduate',course1: 226, p1: "It’s tough to say what my favourite course would have been - all of the 200 level INFO papers were amazing. INFO226 holds a special place in my heart because after studying it, I came back to tutor it the following year. It’s one of those courses that you get out what you put in. If you enjoy complex problem solving and the thrill of finally getting something to work after trying and trying, then this is the course for you. Extremely rewarding." },
        { course: '246', bcolor: 'primary' ,courseName: 'User Experience Design', Points: '15 Points', level: '200', Prerequisites: '101 or 141 or 151', it:'IT' , is: '', tri: 'tri 2', tri2: '2', description: 'This course introduces fundamental principles, standards and best practices of human-computer interaction, usability and user experience ', image: '', icon: 'images/INFO 246.jpg',url: 'https://www.victoria.ac.nz/courses/info/246/2020', coordinator:'' },
        
        
        { course: '354', bcolor: 'success', courseName: 'Digital Strategy', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1',tri1: '1', description: "This course will allow you to develop your competence in seeing how organisations can benefit from digital technology, converting opportunities created by technology into sustainable organisational value. You will learn through discussing cases from well-known companies such as DropBox, Cirque du Soleil, Twitter, Amazon and also from more obscure innovators. ", image: '', icon: 'images/INFO 354.jpg',url: 'https://www.victoria.ac.nz/courses/info/354/2020', coordinator:'' },
        { course: '376', bcolor: 'success' , courseName: 'Enterprise Architecture', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1',tri1: '1', description: "This course addresses the alignment between enterprise goals and strategy, business processes, data, information systems and the technical infrastructure.", image: '', icon: 'images/INFO 376.jpg',url: 'https://www.victoria.ac.nz/courses/info/376/2020', coordinator:'' },
        { course: '334', bcolor: 'warning' , courseName: 'Digital Business Innovation', Points: '15 Points', level: '300', Prerequisites: 'INFO234', it:'' , is: 'BA optional', tri: 'Trimester 3', tri3: '3', description: 'The course focuses on how businesses can adapt information technologies to add innovation to business models, products and services. It will allow you evaluate real life examples and apply your learnings to innovations of your choice. s', image: '', icon: 'images/INFO 334.jpg',url: 'https://www.victoria.ac.nz/courses/info/334/2020', coordinator:'',
        tes: 'Course Testimoials',student: 'Claudia Sullivan,', status: 'Graduate',course1: 334, p1: "INFO334! The course material was engaging and I enjoyed applying the content to real life situations, as we analysed current real-world digital innovations.  Don't knock it till you try it! Also, 200 and 300 level papers are very different to 100 level papers, 100 is an overview of everything possible, whereas when you begin to specialise into different areas, it becomes an exciting and interesting journey!" },
        { course: '388', bcolor: 'warning' , courseName: 'Enterprise Security', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts', it:'' , is: 'BA optional', tri: 'Trimester 1 ', tri1: '1', description: 'This course explores current managerial and technical information security topics. You will learn proven information management approaches, methods, techniques and tools and how to apply these to control prevalent threats and risks.  ', image: '', icon: 'images/INFO 388.jpg',url: 'https://www.victoria.ac.nz/courses/info/388/2020', coordinator:'' },
        { course: '377', bcolor: 'primary' ,courseName: 'System Verification', Points: '15 Points', level: '300', Prerequisites: 'INFO226', it:'IT optional' , is: '', tri: 'Trimester 2', tri2: '2', description: 'In this course you will apply the theory of information systems assurance to design and build test plans for specific systems and software requirements.', image: '', icon: 'images/INFO 377.jpg',url: 'https://www.victoria.ac.nz/courses/info/377/2020', coordinator:'' },
        { course: '386', bcolor: 'primary' , courseName: 'IT Architecture', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts', it:'IT Optional' , is: '', tri: 'Trimester 1', tri1: '1', description: 'This course examines conceptual and physical building blocks of current information and communication infrastructures, including distributed, mobile, pervasive and cloud solutions. In your workshops you will be using Raspberry Pi to explore computing and learn how to program in languages like Scratch and Python.', image: '', icon: 'images/INFO 386.jpg',url: 'https://www.victoria.ac.nz/courses/info/386/2020', coordinator:'' },

        { course: '336', bcolor: 'secondary' ,courseName: 'Social Responsibility - Digital', Points: '15 Points', level: '300', Prerequisites: ' 15 200-level or COMP/ NWEN/SWEN pts', it:'' , is: '', tri: 'Trimester 1', tri1: '1', description: 'This course is a critical examination of the relationship between digital technologies and systems and concerns centred on sustainability and social justice. Topics will focus on current issues regarding both sustainability in the context of organisations, communities, government and society.', image: '', icon: 'images/INFO 336.jpg',url: 'https://www.victoria.ac.nz/courses/info/336/2020', coordinator:'' },
        { course: '360', bcolor: 'secondary' ,courseName: 'IS for Health Care', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts', it:'' , is: '', tri: '', description: 'This course will enable students to apply practical cases using modelling technologies to enable students to acquire and practice the skills necessary to define and implement health information systems.  ', image: '', icon: 'images/INFO 360.jpg',url: 'https://www.victoria.ac.nz/courses/info/360/2020', coordinator:'' },
        { course: '381', bcolor: 'secondary' ,courseName: 'Applied Machine Learning', Points: '15 Points', level: '300', Prerequisites: 'one of INFO264, 281, MATH141, 251, 277', it:'' , is: '', tri: 'Trimester 2', tri2: '2', description: 'In this course you will learn about the principles and applications of advanced machine learning models. You will carry out the preparation and processing required for selecting input data for machine learning models, quantitatively evaluate and qualitatively interpret the outcomes of model learning or prediction ', image: '', icon: 'images/INFO 381.jpg',url: 'https://www.victoria.ac.nz/courses/info/381/2020', coordinator:'' },
        // { course: '391', bcolor: 'secondary' ,courseName: 'Research Paper in Information Systems', Points: '15 Points', level: '300', Prerequisites: 'Permission of Head of School, 30 300-level pts', it:'' , is: '', tri: 'Trimester 1, 2 & 3', description: 'This course is a supervised investigation of information systems issues. The investigation may take the form of a case study, action research, extended research essay, or other research project. ', image: '', icon: 'images/391.jpg',url: 'https://www.victoria.ac.nz/courses/info/391/2020', coordinator:'' },
        { course: '320', bcolor: 'primary' ,courseName: 'Project in IS', Points: '15 Points', level: '300', Prerequisites: 'B+ or better in any 2: 226, 231, 234, 246, 264; & 15 300 pts', it:'IT Capstone' , is: 'BA Capstone', tri: '', description: 'This course provides students with an opportunity to apply their theoretical knowledge to a practical problem in the area of information systems. Students work in teams on real projects for real clients. The course coordinator defines the projects.', image: '', icon: 'images/INFO 320.jpg',url: 'https://www.victoria.ac.nz/courses/info/320/2020', coordinator:'',
        tes: 'Course Testimoials',student: 'Hayley Skelton,', status: 'Graduate',course1: 320, p1: "INFO320 (Projects in Information Systems), in my opinion it is the perfect capstone to an INFO major. It was great to have the opportunity to use all I'd learned throughout my degree in a real project. Getting some real experience of communicating with stakeholders, solving issues, ensuring deliverables are on time and giving a presentation of your ideas was invaluable." },
        { course: '395', bcolor: 'warning' , courseName: 'Case Studies in IS', Points: '15 Points', level: '300', Prerequisites: '30 200-level pts, and 15 300-level pts', it:'' , is: 'BA Capstone', tri: 'Trimester 2', tri2: '2', description: 'In this course you will analyse the human, organisational, and environmental perspective of the impact of new or existing information systems, including management of IT-induced change. ', image: '', icon: 'images/INFO 395.jpg',url: 'https://www.victoria.ac.nz/courses/info/395/2020', coordinator:'' ,
        tes: 'Course Testimoials',student: 'Randall Smith,', status: 'Graduate',course1: 395, p1: "INFO395 - Case Studies. I loved the problem solving opportunities offered through this course. I credit this course for the ease of transition I've had into a career with top tier consulting firms. "},
    ];

    $scope.coursetestimoials = [
        { student: 'Randall Smith', status: 'Graduate', course1: 101, p1: "INFO101 was a great launching point into the various specialisations within information systems and critically for me, technical topics were delivered in a very 'business'/ easy to understand manner that meant, as a non-technologist starting off, I was able to get across key technology concepts quickly!"},
        { student: 'Randall Smith', status: 'Graduate',course1: 395, p1: "INFO395 - Case Studies. I loved the problem solving opportunities offered through this course. I credit this course for the ease of transition I've had into a career with top tier consulting firms. "},
        { student: 'Claudia Sullivan', status: 'Graduate',course1: 334, p1: "INFO334! The course material was engaging and I enjoyed applying the content to real life situations, as we analysed current real-world digital innovations.  Don't knock it till you try it! Also, 200 and 300 level papers are very different to 100 level papers, 100 is an overview of everything possible, whereas when you begin to specialise into different areas, it becomes an exciting and interesting journey!"},
        { student: 'Hayley Skelton', status: 'Graduate',course1: 320, p1: "INFO320 (Projects in Information Systems), in my opinion it is the perfect capstone to an INFO major. It was great to have the opportunity to use all I'd learned throughout my degree in a real project. Getting some real experience of communicating with stakeholders, solving issues, ensuring deliverables are on time and giving a presentation of your ideas was invaluable."},
        { student: 'Patrick Miller', status: 'Graduate',course1: 226, p1: "It’s tough to say what my favourite course would have been - all of the 200 level INFO papers were amazing. INFO226 holds a special place in my heart because after studying it, I came back to tutor it the following year. It’s one of those courses that you get out what you put in. If you enjoy complex problem solving and the thrill of finally getting something to work after trying and trying, then this is the course for you. Extremely rewarding."},
        { student: 'Manraj Rahi', status: 'Current Student',course1: 141, p1: "Choosing my favourite paper is tricky. INFO141 was the paper where I felt I gained an appreciation of what a Business Analyst would do and the practical skills required - I found this really valuable. In general, I’ve thoroughly enjoyed the practical elements of the program; actually being given a chance to apply the skills you learn in lectures meant the INFO degree has lived up to - and exceeded - expectations. "},
    ];

    $scope.coursetestimoials = [
        {student: 'Claudia Sullivan', status: 'Graduate', p1 : 'I’m from Christchurch initially, but I love Wellington! It’s a fun and vibrant city that has the perfect balance between student and corporate life. After having looked into the business schools around the country, I decided Victoria offered a degree and a culture which aligned most with me. Initially, I had intentions to complete my degree with a Marketing and Management major, but since taking INFO101, I decided that Information Systems was better suited to me. Every paper since has solidified that interest.', p2: 'My advice to prospective students would be: Don’t knock it ‘til you try it! Even if you don’t love INFO101 like I loved it, the 200 and 300-level papers is when your INFO degree becomes an exciting and interesting journey'},
        {student: 'Shannon Wray', status: 'Graduate', p1 : 'I did IT at school and have always been really into technology. INFO was the perfect major for me because it combined business and technology. I was draw to Computer Science as well but it just made sense to gain similar skills that were more business focused. I really enjoyed taking info. I loved the variability in the papers we could choose from, I made heaps of friends through INFO and the way the papers are taught enable you to tailor the learning styles to suit yourself. You can either go off and figure it out your self and get help from the tutors when you need or you can follow along with everyone else.'},
        {student: 'Hayley Skelton', status: 'Graduate', p1 : "Once I'd decided I wanted to go to University I did some research. I had a rough idea that Information Systems was what I wanted to major in (see answer to 'what would you consider the turning point..'). This idea was solidified after I perused what VUW had to offer in IS. I really enjoyed that there were different areas of IS (such as security, analysis, modelling, interface design, etc) that I could specialise into as I saw fit. This allowed me to tailor my skillset to what I found most interesting/helpful - I didn't simply have a list of papers I was 'locked' into doing in order to complete my degree."},
        {student: 'Patrick Miller', status: 'Graduate', p1 : 'I’m from Christchurch initially, but I love Wellington! It’s a fun and vibrant city that has the perfect balance between student and corporate life. After having looked into the business schools around the country, I decided Victoria offered a degree and a culture which aligned most with me. Initially, I had intentions to complete my degree with a Marketing and Management major, but since taking INFO101, I decided that Information Systems was better suited to me. Every paper since has solidified that interest.'},
        {student: 'Manraj Rahi', status: 'Current Student', p1 : 'What attracted me to studying IS was the belief that this major provides a future-focused education and an understanding of business and the commercial world. I also felt it would complement my law degree with a unique set of skills through a different learning area.'},
    ];

    $scope.jobs = [
        { Job: 'User Experience Designer', description: 'A UX designer is responsible for how a website or a software application looks and works.', image: 'images/UX designer.png', icon: 'https://www.roberthalf.com/sites/default/files/styles/full_width_content_image_1x_small_480/public/Media_Root/images/blog-tcg/ux-careers-tcg-07-2016.jpg?itok=GTYRFKju', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$55K-$100K per year', opportunities: 'Good' },
        { Job: 'Application Developer', description: 'An application developer is responsible for creating, testing and programming apps.', image: '', icon: 'https://icon-library.net/images/app-development-icon/app-development-icon-2.jpg', skills:'', pay: '', opportunities: '' },
        { Job: 'Information Technology Architect', description: 'An IT architect manages the security architecture and business plans of an organisation. They also create and implement security systems and architectures.', image: 'images/It Architect.png', icon: 'https://openviewpartners.com/wp-content/uploads/2016/10/67059ol4qntmlha-2.jpg', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        { Job: 'Test Analyst', description: 'Test analysts design and carry out testing processes for new and upgraded computer software and systems, analyse the results, and identify and report problems.', image: 'images/Test analyst.png', icon: 'https://hackernoon.com/hn-images/0*xMaFF2hSXpf_kIfG.jpg', skills:'', pay: '$70K-$98K per year', opportunities: 'Good' },
        { Job: 'Enterprise Architect', description: 'The primary role of the Enterprise Architect is to ensure that the respective business, application, data and technology perspectives are in line with the organisation’s technology and governance strategies, policies and standards.', image: '', icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb7IC8bDSDn3nbV1inp4m-d7hmHn9_Qy3QFZQUmHddiui4-acY', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '', opportunities: 'Good' },
        { Job: 'Start-up Entrepreneur', description: 'A Start-up Entrepreneur initiate a company or project to seek, effectively develop and validate a scalable business model.', image: '', icon: 'https://www.keenyakelly.com/wp-content/uploads/2018/06/entrepreneur-1024x768-5a1ba4661f.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '', opportunities: 'Good' },
        { Job: 'Management / IT Consultant', description: 'Help businesses improve their performance and grow by solving problems and finding new and better ways of doing things.', image: 'images/Management_IT consultant.png', icon: 'https://www.arizonamediaz.com/assets/images/featured_imgs/it_consultant_img.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$49K-$137K per years', opportunities: 'Average' },
        { Job: 'IT Project Manager', description: 'IT Project Managers plan, organise, execute and close organisations specific information technology goals.', image: 'images/Data analyst.png', icon: 'https://cdn2.iconfinder.com/data/icons/business-people-20/50/73-512.png', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$55K-$135K per years', opportunities: 'Good' },
        { Job: 'Business information manager', description: 'A Business Information Manager carries out the development and implementation of software applications within a company.', image: '', icon: 'https://cdn1.iconfinder.com/data/icons/database-and-storage-2/49/58-512.png', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '', opportunities: 'Good' },
        { Job: 'Data Analyst', description: 'A data analyst’s job is to take data that businesses collect and use it to help companies make better business decisions.', image: 'images/Data analyst.png', icon: 'https://image.freepik.com/free-vector/big-data-cloud-vector-illustration_1010-667.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$69K-$110K per years', opportunities: 'Good' },
        { Job: 'Security Analyst', description: 'Security analyst’s plan and carry out security measures to protect a company’s computer networks and systems.', image: 'images/Sec analyst.png', icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPiy4k0oSVCS5tNxrTNUAbQ1RvliFSYOq1TWE9Ub5hT6w5t4j_', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$92K-$137K per years', opportunities: 'Good' },
        { Job: 'Business Analyst', description: 'A business analyst is someone who analyses a company or businesses domain and documents its business, processes and systems.', image: 'images/BA.png', icon: 'https://cdn1.iconfinder.com/data/icons/business-characters-2/66/78-512.png', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$81K-$104K per years', opportunities: 'Good' },
        { Job: 'Software Developer', description: 'A Software Developer plays a key role in the design, installation, testing and maintenance of software systems.', image: 'images/Software dev.png', icon: 'https://res.cloudinary.com/practicaldev/image/fetch/s--_HBZhuhF--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/nweeqf97l2md3tlqkjyt.jpg', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$72K-$100K per years', opportunities: 'Good' }
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },
        // { Job: 'Information Technology Architect', description: '', image: '', icon: 'https://miro.medium.com/max/1110/0*wptLbt4cS24GzFdQ', url: 'https://www.victoria.ac.nz/courses/info/101/2020', skills:'', pay: '$120K-$152K per years', opportunities: 'Good' },


        // { course: 'INFO 141', courseName: 'Systems Analysis', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 2', description: 'This course covers the business analysis and system analysis activities, from the perspective of a business analyst. It introduces basic techniques for analysing data flows, as well as the strategies used for determining requirements. It introduces object-oriented modelling.', image: '', icon: 'https://www.learntek.org/blog/wp-content/uploads/2018/05/BA2.jpg',url: 'https://www.victoria.ac.nz/courses/info/141/2020', coordinator:'' },
        // { course: 'INFO 151', courseName: 'Databases', Points: '15 Points', level: '100', Prerequisites: '', it:'IT' , is: 'BA', tri: 'Trimester 1 and 3', description: 'This course introduces the principles of database definition, design, access and implementation. It shows how databases support modern data processing systems. Students will be able to create a data model from a business situation, implement a database from that data model and use query language such as SQL to access data.', image: '', icon: "https://cdn.cnetcontent.com/10/43/104355de-bbe4-42fc-9181-87bf7fe7aa05.jpg",url: 'https://www.victoria.ac.nz/courses/info/151/2020', coordinator:'' },
        // { course: 'INFO 226', courseName: 'Application Development', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'IT' , is: '', tri: 'Trimester 1 ', description: 'An introduction to the use of software languages and tools for rapid application development. The course takes students through the process of translating business requirements, expressed with functional and structural models, into business applications.', image: '', icon: 'https://image.freepik.com/free-vector/application-development-background_1300-165.jpg',url: 'https://www.victoria.ac.nz/courses/info/226/2020', coordinator:'' },
        // { course: 'INFO 231', courseName: 'Management of IT Projects', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141 or 151, or 15 COMP pts', it:'IT' , is: 'BA', tri: 'Trimester 1', description: 'A detailed examination of IT project management including scheduling, monitoring and control techniques. Students will gain an appreciation of IT risk management, change management strategies for internal and external stakeholders, and social and cultural issues arising in multicountry project team environments.', image: '', icon: 'https://thumbs.dreamstime.com/b/gantt-progress-line-flip-chart-white-board-vector-illustration-85089746.jpg',url: 'https://www.victoria.ac.nz/courses/info/231/2020', coordinator:'' },
        // { course: 'INFO 234', courseName: 'Business Process Design', Points: '15 Points', level: '200', Prerequisites: 'INFO101, 141, or 151', it:'' , is: 'BA', tri: ' Trimester 2', description: 'This course will explore the role and potential of IT to support business process management and design. Students learn a modern business process modelling technique, apply that to designing an improved business process, then test and evaluate their proposed design using simulation software.', image: '', icon: 'https://www.michiganstateuniversityonline.com/wp-content/uploads/sites/3/2018/05/how-business-analytics-can-help-your-business.jpg?w=715&h=375&crop=1',url: 'https://www.victoria.ac.nz/courses/info/234/2020', coordinator:'' },
        // { course: 'INFO 246', courseName: 'User Experience Design', Points: '15 Points', level: '200', Prerequisites: '', it:'IT' , is: '', tri: 'INFO101, 141 or 151.', description: 'Introduces fundamental principles, standards and best practices of human-computer interaction, usability and user experience. Advanced software tools enable students to create low-fidelity and high-fidelity userinterfaces for business websites and applications and covers the full lifecycle of user-interface design, from requirements specification to design, prototyping, and evaluation.', image: '', icon: 'https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2016/08/shutterstock_277867241-796x796.jpg',url: 'https://www.victoria.ac.nz/courses/info/246/2020', coordinator:'' },
        // { course: 'INFO 264', courseName: 'Business Analytics', Points: '15 Points', level: '200', Prerequisites: 'INFO151', it:'' , is: 'BA', tri: 'Trimester 2', description: 'Covers the techniques of collecting, organising and analysing historic data to improve business processes and predict customer behaviour. Uses analytical software for data mining, decision support, supply chain management, simulation, and optimisation', image: '', icon: 'https://image.freepik.com/free-vector/business-analytics-vector_28257-13.jpg',url: 'https://www.victoria.ac.nz/courses/info/264/2020', coordinator:'' },
        // { course: 'INFO 320', courseName: 'Project in Information Systems', Points: '15 Points', level: '300', Prerequisites: 'B+ or better in any two of INFO 226, 231, 234, 246, 264; & 15 INFO 300-level points', it:'IT Capstone' , is: 'BA', tri: '', description: 'This course provides students with an opportunity to apply their theoretical knowledge to a practical problem in the area of information systems. Students work in teams on real projects for real clients. The course coordinator defines the projects.', image: '', icon: 'https://www.cio.co.uk/cmsdata/slideshow/3647302/istock-peopleimages_thumb350.jpg',url: 'https://www.victoria.ac.nz/courses/info/320/2020', coordinator:'' },
        // { course: 'INFO 334', courseName: 'Digital Business Innovation', Points: '15 Points', level: '300', Prerequisites: 'INFO234', it:'' , is: 'BA optional', tri: 'Trimester 3', description: 'The course focuses on how businesses can adapt information technologies to add innovation to business models, products and services. It includes an evaluation of digital strategies to support other corporate initiatives and how to integrate innovative business models such as social media and e-commerce to build customer relationships and improve the customer experience.', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/334/2020', coordinator:'' },
        // { course: 'INFO 336', courseName: 'Social Responsibility in a Digital World', Points: '15 Points', level: '300', Prerequisites: ' 15 200-level INFO or COMP/ NWEN/SWEN pts', it:'' , is: '', tri: 'Trimester 1', description: 'A critical examination of the relationship between digital technologies and systems and concerns centred on sustainability and social justice. Topics will focus on current issues regarding both sustainability (e.g. clean energy, climate change, innovation, and sustainable cities) and ethics (e.g. inequality, digital divide, privacy, and professional codes of conduct) in the context of organisations, communities, government and society', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/336/2020', coordinator:'' },
        // { course: 'INFO 354', courseName: 'Digital Strategy', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1', description: "This course addresses the alignment between enterprise goals and strategy, business processes, data, information systems and the technical infrastructure. Students learn about enterprise architecture's role in digital transformations, how to analyse, model, design and evaluate enterprise architectures, how to plan the transition from a baseline to a target architecture, and how to create effective governance instruments for successful enterprise architecture management.", image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/354/2020', coordinator:'' },
        // { course: 'INFO 360', courseName: 'Information Systems for Health Care', Points: '15 Points', level: '300', Prerequisites: '', it:'' , is: '', tri: '', description: 'Text', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/360/2020', coordinator:'' },
        // { course: 'INFO 376', courseName: 'Enterprise Architecture', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'IT Optional' , is: 'BA Optional', tri: 'Trimester 1', description: "This course addresses the alignment between enterprise goals and strategy, business processes, data, information systems and the technical infrastructure. Students learn about enterprise architecture's role in digital transformations, how to analyse, model, design and evaluate enterprise architectures, how to plan the transition from a baseline to a target architecture, and how to create effective governance instruments for successful enterprise architecture management.", image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/376/2020', coordinator:'' },
        // { course: 'INFO 377', courseName: 'System Verification', Points: '15 Points', level: '300', Prerequisites: 'INFO226s', it:'IT optional' , is: '', tri: 'Trimester 2', description: 'Critically evaluate theory and heuristics of test design, planning and implementation. Apply the theory of information systems assurance to design and build test plans for specific systems and software requirements. Implement key components of program testing, logic testing and user acceptance testing.', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/377/2020', coordinator:'' },
        // { course: 'INFO 381', courseName: 'Special Topic: Topics in Applied Machine Learning', Points: '15 Points', level: '300', Prerequisites: '', it:'' , is: '', tri: 'Trimester 2', description: '', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/381/2020', coordinator:'' },
        // { course: 'INFO 386', courseName: 'Information Technology Architecture', Points: '15 Points', level: '300', Prerequisites: 'Trimester 1 ', it:'IT Optional' , is: '', tri: '', description: 'This course examines conceptual and physical building blocks of current information and communication infrastructures, including distributed, mobile, and pervasive and cloud solutions. The course describes how the internet is used as a platform for developing business applications, and uses practical technologies to enable students to model and design IT architectures from a business perspective.', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/386/2020', coordinator:'' },
        // { course: 'INFO 388', courseName: 'Enterprise Security', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts', it:'' , is: 'BA optional', tri: 'Trimester 1 ', description: 'This course examines conceptual and physical building blocks of current information and communication infrastructures, including distributed, mobile, and pervasive and cloud solutions. The course describes how the internet is used as a platform for developing business applications, and uses practical technologies to enable students to model and design IT architectures from a business perspective.', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/388/2020', coordinator:'' },
        // { course: 'INFO 391', courseName: 'Research Paper in Information Systems', Points: '15 Points', level: '300', Prerequisites: '', it:'' , is: '', tri: '', description: 'Text', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/391/2020', coordinator:'' },
        // { course: 'INFO 395', courseName: 'Case Studies in Information Systems', Points: '15 Points', level: '300', Prerequisites: '30 200-level INFO pts, and 15 300-level INFO pts', it:'' , is: 'BA Capstone', tri: 'Trimester 2', description: 'A human, organisational, and environmental perspective of the impact of new or existing information systems, including management of IT-induced change.', image: '', icon: 'images/p1.png',url: 'https://www.victoria.ac.nz/courses/info/395/2020', coordinator:'' },
    ];
});



  